language: sh

services:
  - docker

before_install:
- sudo chmod +x ./bootstrap.sh
- docker build --rm -f Dockerfile -t engine-algorithms:latest .

script:
- docker run engine-algorithms:latest
