language: sh

services:
  - docker

before_install:
- docker build --rm -f Dockerfile -t engine-algorithms:latest .
- sudo chmod +x ./bootstrap.sh
- docker run engine-algorithms:latest ./bootstrap.sh -y -e -j2

script:
- echo "done"