language: sh

services:
  - docker

before_install:
- docker build --rm -f \"Dockerfile\" -t engine-algorithms:latest .
- docker run engine-algorithms:latest ./bootstrap.sh -y -e -j2

script:
- echo "done"