cmake_minimum_required(VERSION 2.8.2)
include(ExternalProject)

ExternalProject_Add(googletest PREFIX googletest
  GIT_REPOSITORY    https://github.com/google/googletest.git
  GIT_TAG           release-1.8.1

  UPDATE_COMMAND ""

  CMAKE_ARGS
    "-DINSTALL_GTEST=OFF"

  CMAKE_CACHE_ARGS
    "-DCMAKE_C_COMPILER:FILEPATH=${CMAKE_C_COMPILER}"
    "-DCMAKE_CXX_COMPILER:FILEPATH=${CMAKE_CXX_COMPILER}"

  INSTALL_COMMAND echo <INSTALL_DIR>

  LOG_DOWNLOAD 1 LOG_UPDATE 1 LOG_CONFIGURE 1 LOG_BUILD 1 LOG_INSTALL 1
)

ExternalProject_Get_Property(googletest INSTALL_DIR)

set(GOOGLETEST_INCLUDE_DIR ${INSTALL_DIR}/include)

set(GOOGLETEST_LIBRARIES
    ${INSTALL_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}GOOGLETEST${CMAKE_STATIC_LIBRARY_SUFFIX})

set(GOOGLETEST_INCLUDE_DIRS ${GLEW_INCLUDE_DIRS} CACHE STRING "")
set(GOOGLETEST_LIBRARIES ${GLEW_LIBRARIES} CACHE STRING "")
