cmake_minimum_required(VERSION 2.8.2)
include(ExternalProject)

ExternalProject_Add(sfml PREFIX sfml
    GIT_REPOSITORY https://github.com/SFML/SFML.git
    GIT_TAG 2.5.1

    UPDATE_COMMAND ""

    CMAKE_ARGS
        "-DBUILD_SHARED_LIBS=FALSE"
        "-DSFML_BUILD_AUDIO=FALSE"
        "-DSFML_BUILD_NETWORK=FALSE"
        "-DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>"

    LOG_DOWNLOAD 1 LOG_UPDATE 1 LOG_CONFIGURE 1 LOG_BUILD 1 LOG_INSTALL 1 LOG_OUTPUT_ON_FAILURE 1
)

ExternalProject_Get_Property(sfml INSTALL_DIR)
set(SFML_INCLUDE_DIR ${INSTALL_DIR}/include)
set(SFML_LIBS
    ${INSTALL_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}sfml-graphics-s${CMAKE_STATIC_LIBRARY_SUFFIX}
    ${INSTALL_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}sfml-system-s${CMAKE_STATIC_LIBRARY_SUFFIX}
    ${INSTALL_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}sfml-window-s${CMAKE_STATIC_LIBRARY_SUFFIX}
)
